import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'

export interface PDFTableSection {
  title?: string
  headers: string[]
  rows: (string | number | null | undefined)[][]
}

export interface PDFDocumentOptions {
  title: string
  subtitle?: string
  sections: PDFTableSection[]
  generatedBy?: string
}

/**
 * Generates a PDF report buffer with title, optional subtitle,
 * and one or more tables. Uses jsPDF + jspdf-autotable.
 */
export function generatePDF(options: PDFDocumentOptions): Buffer {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' })

  const pageW = doc.internal.pageSize.getWidth()
  let y = 15

  // Title
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text(options.title, pageW / 2, y, { align: 'center' })
  y += 8

  // Subtitle
  if (options.subtitle) {
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.text(options.subtitle, pageW / 2, y, { align: 'center' })
    y += 6
  }

  // Generated timestamp
  const genBy = options.generatedBy ?? 'AI Email Agent'
  doc.setFontSize(8)
  doc.setTextColor(120)
  doc.text(
    `Generated by ${genBy} on ${new Date().toLocaleString()}`,
    pageW / 2,
    y,
    { align: 'center' },
  )
  y += 10
  doc.setTextColor(0)

  // Sections
  for (const section of options.sections) {
    if (section.title) {
      doc.setFontSize(12)
      doc.setFont('helvetica', 'bold')
      doc.text(section.title, 14, y)
      y += 6
    }

    autoTable(doc, {
      startY: y,
      head: [section.headers],
      body: section.rows.map(row =>
        row.map(cell => (cell === null || cell === undefined ? '' : String(cell))),
      ),
      styles: { fontSize: 9, cellPadding: 2 },
      headStyles: { fillColor: [41, 128, 185], textColor: 255, fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [245, 245, 245] },
      margin: { left: 14, right: 14 },
      didDrawPage: (data) => {
        y = (data.cursor?.y ?? y) + 10
      },
    })

    y = ((doc as any).lastAutoTable?.finalY ?? y) + 12
  }

  return Buffer.from(doc.output('arraybuffer'))
}

export const PDF_MIME = 'application/pdf'
